### ISSUE TITLE
Does this extension change the way JupyterLab routes URL paths?

### ISSUE THREAD

**Issue by justinbois** [bokeh/jupyterlab_bokeh#42] opened 2018-06-09 17:38 UTC
Referencing [this issue](https://github.com/altair-viz/altair/issues/927) I raised on the Altair repository....

**The short**: When I have the jupyterlab_bokeh extension installed, rendering Vega-Lite graphics via Altair fails if I reference the data by URL. Does this extension change the way JupyterLab routes URL paths?

**The long**: If I launch a notebook in freshly installed JupyterLab with a code cell containing the following code, everything runs fine.

```python
import altair as alt

alt.Chart('test.json').mark_line().encode(x='x:Q', y='y:Q')
```

where the contents of `test.json` are:

```
[{"x":0,"y":0},{"x":1,"y":1}]
```

However, if I install the `jupyter_bokeh` labextension, The chart is not populated with data.

Disabling the `jupyter_bokeh` labextension does not solve the problem, nor does uninstalling it. Uninstalling and reinstalling JupyterLab does work.

Perhaps the jupyterlab_bokeh extension is changing the way JupyterLab accesses URLs? I would love to be able to use Altair and Bokeh seamlessly in my projects, so any help or fixes are appreciated.

System information
```
CPython 3.6.5
IPython 6.4.0

jupyterlab_bokeh: 0.5.0
jupyterlab 0.32.1
altair 2.1.0

compiler   : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
system     : Darwin
release    : 17.5.0
machine    : x86_64
processor  : i386
CPU cores  : 8
interpreter: 64bit
```

**Comment by canavandl** [comment] 2018-07-08 19:56
@justinbois I don't believe that jupyterlab_bokeh is the culprit here, our extension is a pretty basic mime-renderer extension and we don't modify any requests. Somebody suggested that ``@jupyter-widgets/jupyterlab-manager`` is stripping request cookies and causing altair to fail (https://github.com/matplotlib/jupyter-matplotlib/issues/53), do you have that extension installed and are able to confirm that it's the problem?

**Comment by canavandl** [comment] 2018-07-08 23:04
On further investigation, I think the cause may be more complex than just jupyterlab_bokeh and jupyterlab_matplotlib. I was able to reproduce the issue in an environment with several custom JLab extensions and serverextensions, but was able to resolve the issue by upgrading IPython to the 6.x series. I hope that helps.

**Comment by bryevdv** [comment] 2018-10-01 01:47
closing for lack of follow up/further reports, and lack of clear evidence that the bokeh extension is the issue.

**Closed by bryevdv** 2018-10-01 01:47 UTC

**Comment by justinbois** [comment] 2018-10-01 02:49
FWIW, the extension and Altair rendering are working now with newest version of Jupyter, at least on my machine and that of others I work with.
