### ISSUE TITLE
Tooltips not populating

### ISSUE THREAD

**Issue by ChristopherPAndrews** [bokeh/jupyterlab_bokeh#55] opened 2018-09-04 20:39 UTC
I tried the basic tooltip example from the bokeh guide, modified for the notebook and in jupyter lab the tooltip appears, and the labels are present, but not the values -- they are just blank.

~~~
from bokeh.plotting import figure, show, ColumnDataSource
from bokeh.io import output_notebook

# set the output to the notebook
output_notebook()

source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=['A', 'b', 'C', 'd', 'E'],
))

TOOLTIPS = [
    ("index", "$index"),
    ("(x,y)", "($x, $y)"),
    ("desc", "@desc"),
]

p = figure(plot_width=400, plot_height=400, tooltips=TOOLTIPS,
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)
~~~

**Comment by mauermbq** [comment] 2018-10-17 22:59
I've the same problem. 
Package manager also reported a compatibility problem during isntallation:
`Node v8.12.0

> /conda/bin/npm pack jupyterlab_bokeh
npm notice
npm notice 📦  jupyterlab_bokeh@0.6.2
npm notice === Tarball Contents ===
npm notice 1.2kB package.json
npm notice 1.5kB LICENSE.txt
npm notice 1.1kB README.md
npm notice 64B   lib/index.d.ts
npm notice 151B  lib/index.js
npm notice 540B  lib/manager.d.ts
npm notice 974B  lib/manager.js
npm notice 577B  lib/plugin.d.ts
npm notice 1.6kB lib/plugin.js
npm notice 1.4kB lib/renderer.d.ts
npm notice 4.9kB lib/renderer.js
npm notice === Tarball Details ===
npm notice name:          jupyterlab_bokeh
npm notice version:       0.6.2
npm notice filename:      jupyterlab_bokeh-0.6.2.tgz
npm notice package size:  4.6 kB
npm notice unpacked size: 14.0 kB
npm notice shasum:        080668537cc2dabb16ba7f7fc3ed68c7123599a8
npm notice integrity:     sha512-9qDpssWSFrT8o[...]cy9dA4UKWuklA==
npm notice total files:   11
npm notice
jupyterlab_bokeh-0.6.2.tgz
Incompatible extension:

"jupyterlab_bokeh@0.6.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.18.2 <0.19.0 @jupyterlab/application
>=0.19.1 <0.20.0        >=0.18.2 <0.19.0 @jupyterlab/apputils
>=0.19.2 <0.20.0        >=0.18.2 <0.19.0 @jupyterlab/notebook

Found compatible version: 0.2.0
> /conda/bin/npm pack jupyterlab_bokeh@0.2.0
npm notice
npm notice 📦  jupyterlab_bokeh@0.2.0
npm notice === Tarball Contents ===
npm notice 779B  package.json
npm notice 449B  README.md
npm notice 3.9kB lib/index.js
npm notice 1.1kB lib/index.d.ts
npm notice === Tarball Details ===
npm notice name:          jupyterlab_bokeh
npm notice version:       0.2.0
npm notice filename:      jupyterlab_bokeh-0.2.0.tgz
npm notice package size:  2.1 kB
npm notice unpacked size: 6.2 kB
npm notice shasum:        92f9b8bc93ddb9889f98594d5e5ad13a1c2d1cce
npm notice integrity:     sha512-kUnjyew6G4imN[...]WvH/fODa7PE2A==
npm notice total files:   4
npm notice
jupyterlab_bokeh-0.2.0.tgz`

**Comment by canavandl** [comment] 2018-10-26 02:44
@ChristopherPAndrews I was unable to reproduce your issue using JupyterLab=0.35.2 and Bokeh=1.0.0, so i'd suggest upgrading if you still have a problem. I'm going to close this as "resolved", please re-open if you still have an issue.

@mauermbq your issue appears to be that you have a pretty old version of JupyterLab that's compatible with an old version of jupyterlab_bokeh. I'd suggest upgrading to JupyterLab=0.35.2 and Bokeh=1.0.0, if possible.

**Closed by canavandl** 2018-10-26 02:44 UTC

**Comment by mauermbq** [comment] 2018-10-26 09:11
unfortunately there is still an isue #60

**Comment by bryevdv** [comment] 2019-07-10 02:18
This is working for me with Bokeh 1.2 and extension 1.0.0next, so closing. I will note the value text is black, so if you are using a "dark" theme or something, that might explain things. I think for now you would have to target CSS to change bokeh built-in text props, but could use a custom tooltip to set whatever CSS/HTML you need.
