### ISSUE TITLE
UnboundLocalError: local variable 'proc' referenced before assignment

### ISSUE THREAD

**Issue by cecilialee** [bokeh/jupyterlab_bokeh#5] opened 2017-09-18 00:31 UTC
When I try to install using `jupyter labextension install jupyterlab_bokeh`, terminal outputed `UnboundLocalError: local variable 'proc' referenced before assignment`.

What's wrong here??

**Comment by dhirschfeld** [comment] 2017-09-18 01:03
Anyone trying to help will likely need a lot more context - i.e. paste the full output of the command up until the final error you have shown above.

**Comment by juusokorhonen** [comment] 2018-01-06 09:32
I ran into the same issue. The error message is not particularly helpful. The problem for me was missing nodejs installation, which (for me) was corrected by `conda install nodejs`.

**Comment by sushiterry** [comment] 2018-02-01 20:05
I can confirm that installing nodejs in my Anaconda install also fixed the issue.

It looks like stock Anaconda installs will probably hit this, unless they've had reason to install the nodejs package.  Is nodejs properly configured as a dependency and installed as part of installing this plugin, or is the user expected to do that?

**Comment by blink1073** [comment] 2018-02-01 20:22
Hi @sushiterry, what is the output of `jupyter lab --version`?  In theory, Anaconda could ship with the `nodejs` package, but it would override the user's system installed version if they had one.

**Comment by sushiterry** [comment] 2018-02-01 23:02
I don't think it does ship with nodejs.

Unfortunately I already updated my jupyter lab version because I ran into another issue installing the plugin.

The working version for me is 0.31.2.

**Comment by blink1073** [comment] 2018-02-03 22:27
The `UnboundLocalError` is a known bug in older versions.  It should now tell you to install `nodejs` if it is not found.

**Comment by canavandl** [comment] 2018-02-19 04:15
I'm going to close this as resolved. Thanks for the report @cecilialee - please reopen this or a new issue if you still have problems.

**Closed by canavandl** 2018-02-19 04:15 UTC
